In [1]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [22]:
a = np.random.rand(2,2)
a

array([[0.66335133, 0.03012951],
       [0.46500682, 0.47238441]])

In [18]:
b = np.random.randn(5)
b

array([-0.50790258, -2.69002024,  0.65190825, -1.3241899 , -0.31275038])

In [31]:
c = np.random.randint(10,50 , size=(2,2))
c

array([[15, 28],
       [39, 36]])

In [55]:
# seed -> 동일한 값
np.random.seed(5)
d = np.random.randn(5)
d

array([ 0.44122749, -0.33087015,  2.43077119, -0.25209213,  0.10960984])

In [79]:
e = np.random.choice(10,3)  # , 파라미터 True or False
e

array([7, 6, 0])

In [106]:
# 임의의 값으로 (3,2) 형태의 ndarray를 생성
np.random.seed(99)
f = np.random.rand(3,2)
f

array([[0.67227856, 0.4880784 ],
       [0.82549517, 0.03144639],
       [0.80804996, 0.56561742]])

In [137]:
g = np.random.choice(45,6, False)+1  # , 파라미터 True or False
g

array([18,  3, 35, 31, 40, 26])

In [143]:
h = np.random.choice(10,12)
h       

array([2, 3, 7, 6, 8, 7, 7, 6, 6, 4, 6, 3])

In [144]:
i = h.reshape(3,4)
i

array([[2, 3, 7, 6],
       [8, 7, 7, 6],
       [6, 4, 6, 3]])

In [148]:
j = h.reshape(2,3,2)
j

array([[[2, 3],
        [7, 6],
        [8, 7]],

       [[7, 6],
        [6, 4],
        [6, 3]]])

In [150]:
k = h.reshape(2,-1,3)
k

array([[[2, 3, 7],
        [6, 8, 7]],

       [[7, 6, 6],
        [4, 6, 3]]])

In [156]:
l = np.arange(1, 11)
print(l)
l[5]

[ 1  2  3  4  5  6  7  8  9 10]


6

In [279]:
m = np.arange(1,9).reshape(2,2,2)

In [280]:
print(m)
print(m[1,1,0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
7


In [205]:
n = np.arange(1,10).reshape(3,3)
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [244]:
print(n[0:1,1:3])
print(n[1:2,1:3])

[[2 3]]
[[5 6]]


In [228]:
o = np.arange(1,28).reshape(3,3,3)
o

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [229]:
o[2:3,:,0:2]

array([[[19, 20],
        [22, 23],
        [25, 26]]])

In [230]:
o[2,:,0:2]

array([[19, 20],
       [22, 23],
       [25, 26]])

In [256]:
p = np.arange(1,10).reshape(3,3)
p

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [257]:
print(p[[0,2],:])
print(p[[0,2],2])

[[1 2 3]
 [7 8 9]]
[3 9]


In [270]:
# Boolean Index
q = p > 3
print(p)
q

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [275]:
mask = p > 3
print(mask)
p[mask]

[[False False False]
 [ True  True  True]
 [ True  True  True]]


array([4, 5, 6, 7, 8, 9])

In [276]:
mask = (p > 3) & (p < 8)
print(mask)
p[mask]

[[False False False]
 [ True  True  True]
 [ True False False]]


array([4, 5, 6, 7])

In [298]:
arr1 = np.random.randint(10 ,size=9)
arr2 = np.random.randint(10, size=9)
print(arr1)
print(arr2)

[6 4 7 5 1 1 9 2 0]
[2 6 9 1 2 8 9 0 9]


In [310]:
np.add(arr1, arr2)

array([ 8, 10, 16,  6,  3,  9, 18,  2,  9])

In [303]:
np.subtract(arr1, arr2)

array([ 4, -2, -2,  4, -1, -7,  0,  2, -9])

In [306]:
np.multiply(arr1, arr2)

array([12, 24, 63,  5,  2,  8, 81,  0,  0])

In [308]:
np.divide(arr1, arr2)

array([3.        , 0.66666667, 0.77777778, 5.        , 0.5       ,
       0.125     , 1.        ,        inf, 0.        ])

In [311]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(3)
arr1 + arr2

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [374]:
arr1 = np.random.rand(10).reshape(2,5)
arr1.mean()

0.4822621362231434

In [385]:
arr1

array([[0.8622242 , 0.55155768, 0.15028921, 0.29992067, 0.07768957],
       [0.80911331, 0.09490048, 0.93057719, 0.44959802, 0.59675105]])

In [381]:
arr1.max()

0.9305771928025368

In [382]:
np.max(arr1)

0.9305771928025368

In [383]:
arr1.min()

0.07768956677624139

In [384]:
arr1.argmax()

7

In [387]:
arr1.argmin()

4

In [404]:
np.median(arr1)

0.5005778476027831

In [405]:
np.std(arr1)

0.30468807502072

In [406]:
np.var(arr1)

0.09283482305983187

In [417]:
arr1 = np.arange(12).reshape(3,4)+1
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [418]:
arr1.sum()

78

In [419]:
arr1.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78], dtype=int32)

In [433]:
arr1.sum(axis=0)

array([15, 18, 21, 24])

In [425]:
arr1.sum(axis=1)

array([10, 26, 42])

In [438]:
# axis => 0,1,2/면,행,열
arr2 = np.arange(24).reshape(2,3,4)
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [440]:
arr2.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [441]:
arr2.sum(axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [442]:
arr2.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [445]:
print(arr2 > 5)

[[[False False False False]
  [False False  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


In [446]:
print(np.where(arr2 >5 , True, False))

[[[False False False False]
  [False False  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]
